# Generated by Django 4.0 on 2022-08-04 14:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220802_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
