# Generated by Django 4.0.5 on 2022-08-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_google_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin',
            name='Country',
            field=models.CharField(max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='degree',
            field=models.CharField(max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='first_name',
            field=models.CharField(max_length=20, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='headline',
            field=models.CharField(max_length=200, null=True, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='industry_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Is Student'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='picture_url',
            field=models.URLField(null=True, verbose_name='Picture Url'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='school',
            field=models.CharField(max_length=20, null=True, verbose_name='School'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='study_field',
            field=models.CharField(max_length=20, null=True, verbose_name='Study field'),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='summary',
            field=models.TextField(max_length=2001, null=True, verbose_name='Summary'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill')),
                ('linkedIn_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedin', verbose_name='Linkedin account')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Company name')),
                ('linkedIn_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedin', verbose_name='Linkedin account')),
            ],
        ),
    ]
