# Generated by Django 4.0.5 on 2022-08-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Google', '0001_initial'),
        ('Github', '0001_initial'),
        ('LinkedIn', '0001_initial'),
        ('accounts', '0005_google_created_at_google_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='linkedIn_account',
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Github.github', verbose_name='Github account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Google.google', verbose_name='Google account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LinkedIn.linkedin', verbose_name='LinkedIn account'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Github',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='LinkedIn',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
