# Generated by Django 4.0.5 on 2022-08-11 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('node_id', models.CharField(max_length=50, verbose_name='Node ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('twitter_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Username')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('hireable', models.BooleanField(verbose_name='Hireable')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('avatar_url', models.URLField(verbose_name='Avatar')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('account_created', models.DateTimeField(verbose_name='Github Joined Date')),
                ('followers_url', models.URLField(verbose_name='Followers Url')),
                ('following_url', models.URLField(verbose_name='Following Url')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
    ]
