# Generated by Django 4.0.5 on 2022-08-11 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Last name')),
                ('summary', models.TextField(max_length=2001, null=True, verbose_name='Summary')),
                ('Country', models.CharField(max_length=30, null=True, verbose_name='Country')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('picture_url', models.URLField(null=True, verbose_name='Picture Url')),
                ('industry_name', models.CharField(max_length=20, null=True, verbose_name='Industry')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is Student')),
                ('headline', models.CharField(max_length=200, null=True, verbose_name='Headline')),
                ('school', models.CharField(max_length=20, null=True, verbose_name='School')),
                ('degree', models.CharField(max_length=20, null=True, verbose_name='Degree')),
                ('study_field', models.CharField(max_length=20, null=True, verbose_name='Study field')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill')),
                ('linkedIn_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinkedIn.linkedin', verbose_name='Linkedin account')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Company name')),
                ('linkedIn_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinkedIn.linkedin', verbose_name='Linkedin account')),
            ],
        ),
    ]
